### ISSUE TITLE
I'm a bit lost on how to run it on Steam Deck

### ISSUE THREAD

**Issue by DirkDingleberry** [UnlegitSenpaii/FAE_Linux#16]
Hello, I'm 99.9% sure it's just because I'm a linux newb, though I'm fairly proficient in Windows. I'm trying to run this on my Steam Deck for the native Linux version of the game, but I'm confused by the instructions where it says "run it with the factorio path as a parameter." I dropped the file in the same folder as the Factorio executable, but when I run the FAE_Linux program in Kate, I don't see anywhere to add any parameters. Does anyone have any insight here?

**Comment by UnlegitSenpaii** [comment]
Run the following command, if the patcher and the factorio binary are in the same path.
```
./FAE_Linux factorio
```

**Comment by Mriixi** [comment]
tried that and just say,  No such file or directory,

i am also on steam deck and new to Linux and having a hard time understanding what you mean

**Comment by Mriixi** [comment]
a short video would be extremely help just showing what to do

**Comment by UnlegitSenpaii** [comment]
Can you provide more information? Maybe a screenshot of your terminal where you entered the command?

Make sure the currently selected directory in the terminal is correct.

You do that with `cd /path/to/your/folder`

**Comment by UnlegitSenpaii** [comment]
> a short video would be extremely help just showing what to do  

Not home.

**Comment by Mriixi** [comment]
![Screenshot_20241130_125752](https://github.com/user-attachments/assets/82aec06a-97b5-491b-8b85-8e3cab8bdd05)

**Comment by Mriixi** [comment]
okay im getting closer i think (also learning alot so thank you just for that )
![Screenshot_20241130_131642](https://github.com/user-attachments/assets/e9cc7dc6-a0ae-439c-ab43-7c6dd1daf763)

**Comment by UnlegitSenpaii** [comment]
ouh god. How did you download the patcher? I have a bad feeling...

I hope from here..
https://github.com/UnlegitSenpaii/FAE_Linux/releases/lastest

**Comment by Mriixi** [comment]
i have realized my mistake , i was trying to do all thos for the wrong file, the .cpp file not the patcher 
![Screenshot_20241130_134800](https://github.com/user-attachments/assets/3015d48d-59b8-4c0b-972b-16dd4b5ad0d8)



thank your for you time and help
