### ISSUE TITLE
[BUG]Ubuntu not working

### ISSUE THREAD

**Issue by Fr-Dae** [UnlegitSenpaii/FAE_Linux#18]
**Describe the error**

**Desktop (please complete the following information):**
 - **OS:** Lubuntu 22.04
 - **Kernel**  Linux version 5.15.0-125-generic (buildd@lcy02-amd64-040) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024
- 
 - **Factorio** Version: 2.0.23

**Program Output / Error Output**
Copy Paste the Program or Error Output

**Additional context**
![Capture d’écran du 2024-12-03 15-16-39](https://github.com/user-attachments/assets/7c08e466-370c-4a94-8a7d-f128006f58c1)

how i can install a lib when it's not avalible ?

**Comment by UnlegitSenpaii** [comment]
Have you compiled the project yourself?

It seems that the libraries used to compile the project are newer than the ones available on your system. You should consider updaing your system every once in a while.

If you are unable to compile the project yourself, here are the steps you might want take to remedy your problem.

Check your installed versions of libstdc++:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```

Update them using:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install --only-upgrade libstdc++6
```
[as found here](https://stackoverflow.com/questions/76974555/glibcxx-3-4-32-not-found-error-at-runtime-gcc-13-2-0)
[also found this](https://www.reddit.com/r/Ubuntu/comments/ptixle/is_there_a_ppa_that_always_has_the_latest_gcc/)

Please don't DM me on discord about user specific issues. My discord is reserved to urgent security issues, as descibed in my security advisory.

**Comment by Fr-Dae** [comment]
> Have you compiled the project yourself?
no i jsut take the executable from your releases, make it executable and run it.

why do you still use a old version of this lib if a version 11 exst ?
