### ISSUE TITLE
1.1.76 Update Needed

### ISSUE THREAD

**Issue by sTiKyt** [UnlegitSenpaii/FAE_Linux#2]

**Comment by UnlegitSenpaii** [comment]
@sTiKyt what exactly isnt working?
Make sure to reapply the patch after updating, since the factorio binary gets "unpached" after updating or verifying the gamefiles.

**Comment by UnlegitSenpaii** [comment]
I've pushed & tested my latest build should work with that one.
see [here](https://github.com/UnlegitSenpaii/FAE_Linux/releases/tag/v1.1)
