### ISSUE TITLE
[UPDATE] Works on Version 1.1.80

### ISSUE THREAD

**Issue by Jano1312** [UnlegitSenpaii/FAE_Linux#3]
**Game Information:**
 - Factorio Version: 1.1.80

**Additional context**
Tested on OS: Arch Linux x86_64 Kernel: 6.3.5-arch1-1

Just  wanted  to give the Info, that the Patch works for Version 1.1.80

As I first used the patcher with this version, it was not easy to see if the patcher works, because last verified was 1.1.76.

And the info about not seeing it correctly ingame is very unclear if you use the patcher for the first time:

> I did not find the patterns for AchievementGUI::AchievementGUI.....

There is no easy way to verify it other than unlocking a new achievement to find out if it really works.
Maybe you can make it a bit clearer in the description

Anyways, thank you very much for the patcher

**Comment by UnlegitSenpaii** [comment]
waiting for this https://github.com/NationalSecurityAgency/ghidra/issues/4088
since factorio's debug libraries are in v5
