### ISSUE TITLE
Mac M1 Version?

### ISSUE THREAD

**Issue by DAHines57** [UnlegitSenpaii/FAE_Linux#9]
Same as title. Is there a version of this that works with the M1 mac build?

Thanks

**Comment by UnlegitSenpaii** [comment]
Not that I know of.

GitHub Copilot's opinion is that it shouldn't be that hard to make a port of this for Mac - I wouldn't rely on that, though.

I won't make a port of this for Mac, since I don't have a Mac and don't plan on having one.

Sorry.

**Comment by DAHines57** [comment]
No problem. Thanks for the quick update!
